name: 60s
on:
  # schedule:
  #   - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  _60s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Run
        env:
          XLOG_TOKEN: ${{ secrets.XLOG_TOKEN }}
          XLOG_CHARACTER_ID: ${{ secrets.XLOG_CHARACTER_ID }}
        run: |
          pnpm run build

      - name: Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "update" || exit 0
          git push origin main
